name: ebbinghaus_method
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  sqflite: ^2.2.2
  camera: ^0.10.0+5
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  dartz: ^0.10.1
  google_mlkit_text_recognition: ^0.5.0
  equatable: ^2.0.5
  get_it: ^7.2.0
  image_picker: ^0.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

